services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: stellarts
      POSTGRES_PASSWORD: stellarts_dev
      POSTGRES_DB: stellarts_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stellarts"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  api:
    build: .
    environment:
      DATABASE_URL: postgresql://stellarts:stellarts_dev@db:5432/stellarts_db
      REDIS_URL: redis://redis:6379/0
      SECRET_KEY: dev-secret-key-change-in-production
      DEBUG: "True"
      API_V1_STR: /api/v1
      PROJECT_NAME: Stellarts
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  api-prod:
    build: .
    environment:
      DATABASE_URL: postgresql://stellarts:stellarts_dev@db:5432/stellarts_db
      REDIS_URL: redis://redis:6379/0
      SECRET_KEY: dev-secret-key-change-in-production
      DEBUG: "False"
      API_V1_STR: /api/v1
      PROJECT_NAME: Stellarts
    ports:
      - "8001:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 4

volumes:
  postgres_data:
  redis_data: