from decimal import Decimal


class AIService:
    """
    AI Service for generating smart bids, drafting pitches, and enforcing guardrails.
    """

    @staticmethod
    def calculate_bid_range(
        service_description: str, hourly_rate: Decimal, estimated_hours: float
    ) -> dict:
        """
        Merge labor and materials into an optimal Bid Range.
        Heuristic: Basic material estimation based on service keywords.
        """
        # Default material costs based on common services
        material_estimates = {
            "plumbing": Decimal("80.00"),
            "electrical": Decimal("60.00"),
            "painting": Decimal("100.00"),
            "carpentry": Decimal("120.00"),
            "cleaning": Decimal("20.00"),
        }

        # Determine material cost based on keywords
        material_cost = Decimal("30.00")  # Default
        desc_lower = service_description.lower()
        for keyword, cost in material_estimates.items():
            if keyword in desc_lower:
                material_cost = cost
                break

        labor_cost = Decimal(str(estimated_hours)) * hourly_rate
        total_estimated = labor_cost + material_cost

        # Optimal Range: +/- 10%
        range_min = total_estimated * Decimal("0.9")
        range_max = total_estimated * Decimal("1.1")

        return {
            "labor_cost": labor_cost,
            "material_cost": material_cost,
            "range_min": range_min,
            "range_max": range_max,
            "total_estimated": total_estimated,
        }

    @staticmethod
    def generate_smart_pitch(
        service_description: str,
        material_cost: Decimal,
        labor_cost: Decimal,
        total_cost: Decimal,
        estimated_hours: float,
    ) -> str:
        """
        Draft custom push notifications/pitches.
        Example: "I estimate materials at $120. Claim this 4hr job for $600?"
        """
        return f"I estimate materials at ${material_cost:.2f}. Claim this {estimated_hours}hr job for ${total_cost:.2f}?"

    @staticmethod
    def check_guardrail(counter_offer: Decimal, range_max: Decimal) -> bool:
        """
        Enforce market guardrails.
        Returns True if the counter-offer is > 300% of the calculated max range.
        """
        return counter_offer > (range_max * Decimal("3.0"))

    @staticmethod
    def generate_sow(issue12_output: str, user_voice_intent: str) -> str:
        """
        Combine the parsed job output (Issue-12) with user's voice intent
        to produce a human-readable, markdown Statement of Work (SOW).

        The implementation here uses deterministic templating so it is
        testable and easy to evolve; future improvements may call an LLM
        or a specialized generator.
        """
        title = "# Statement of Work (SOW)\n"

        # Basic sections useful for most job postings
        scope = (
            "## Scope\n"
            "This Statement of Work defines the work to be performed based on the parsed job details and the client's intent.\n\n"
            f"**Parsed job summary:** {issue12_output.strip()}\n\n"
            f"**Client intent / voice:** {user_voice_intent.strip()}\n\n"
        )

        deliverables = (
            "## Deliverables\n"
            "The following deliverables should be produced by the artisan: \n"
            "- Deliverable 1: Implementation matching the job description above.\n"
            "- Deliverable 2: Any intermediate artifacts (photos, wireframes, progress notes) as agreed.\n\n"
        )

        timeline = (
            "## Timeline\n"
            "- Start: Within a mutually agreed window after approval.\n"
            "- Estimated duration: See the booking estimated hours.\n\n"
        )

        acceptance = (
            "## Acceptance Criteria\n"
            "Work will be accepted when the client verifies that the deliverables meet the description and quality expectations.\n"
            "Provide before/after photos where relevant and a short acceptance confirmation message.\n\n"
        )

        payment = (
            "## Payment Terms\n"
            "- Payment will be made per the platform's payment flow.\n"
            "- Any additional costs or change requests must be agreed in writing before execution.\n\n"
        )

        roles = (
            "## Roles & Responsibilities\n"
            "- Client: Provide access, timely feedback, and approvals.\n"
            "- Artisan: Deliver services professionally and communicate delays.\n\n"
        )

        special = (
            "## Special Instructions / Constraints\n"
            "Add any site-specific notes, access constraints, or safety requirements here.\n\n"
        )

        revisions = (
            "## Revision History\n" "- Draft version 1 generated by SOW agent.\n\n"
        )

        # Assemble markdown SOW
        sow_md = (
            title
            + scope
            + deliverables
            + timeline
            + acceptance
            + payment
            + roles
            + special
            + revisions
        )

        return sow_md

    @staticmethod
    def refine_sow(current_content: str, feedback: str) -> str:
        """
        Apply user's iterative feedback into the SOW. For now this function
        merges feedback by appending an "Incorporated Feedback" section and
        tries to inject short feedback lines into the Special Instructions
        if it looks like an instruction (heuristic).
        """
        if not feedback:
            return current_content

        # Heuristic: if feedback contains imperative phrases, add to Special Instructions
        feedback_block = "\n\n## Incorporated Feedback\n" + f"- {feedback.strip()}\n"

        # Try to inject into Special Instructions section if present
        marker = "## Special Instructions / Constraints"
        if marker in current_content:
            parts = current_content.split(marker)
            before = parts[0]
            after = marker + parts[1]
            # insert feedback after the special instructions header (before existing content)
            new_after = (
                marker
                + "\n"
                + f"{feedback.strip()}\n\n"
                + after.replace(marker, "").lstrip()
            )
            refined = before + new_after
        else:
            # Append to the end if no section found
            refined = current_content + feedback_block

        # Add a simple revision note
        refined += f"\n\n<!-- revision: feedback applied -->\n"

        return refined


ai_service = AIService()
